version: '3.7'
#
services:
  iris:
    build:
      context: ./build
    hostname: iris
    container_name: iris

    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"
    volumes:
    - ./cpf:/home/irisowner/cpf

    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
